version: "3.8"

services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgresql://vaultwarden:supersecurepassword@postgres:5432/vaultwarden
      - ADMIN_TOKEN=jcOyPahoV0HQGJsaUhslVyzzSBUBUwLicjvB0v7LKhCyUs51CzYZZF0qGPu61xJD
      - SIGNUPS_ALLOWED=false
      - ADMIN_TOKEN=HierDeinSichererToken
      - PASSWORD_HINTS_ALLOWED=false
      - REQUIRE_DEVICE_EMAIL_CONFIRMATION=true
      - DISABLE_SEND=1
      - PASSWORD_MIN_LENGTH=12
      - PASSWORD_CHECK_HIBP=true
    ports:
      - "8080"
    depends_on:
      - postgres
    networks:
      - vaultwarden_network
    volumes:
      - vaultwarden_data:/data

  postgres:
    image: postgres:15
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=vaultwarden
      - POSTGRES_USER=vaultwarden
      - POSTGRES_PASSWORD=supersecurepassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - vaultwarden_network

networks:
  vaultwarden_network:

volumes:
  vaultwarden_data:
  postgres_data:
